# Generated by Django 4.2.4 on 2023-08-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='macadress',
        ),
        migrations.CreateModel(
            name='MacAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_adress', models.CharField(max_length=30, verbose_name='MacAdress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.agent')),
            ],
        ),
    ]
