# Generated by Django 4.2.4 on 2023-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_macaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddress',
            name='mac_address',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='MacAddress'),
        ),
    ]
