# Generated by Django 4.2.4 on 2023-08-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_macaddress_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bot Name')),
                ('key', models.CharField(max_length=150, verbose_name='Bot Key')),
                ('url', models.CharField(blank=True, max_length=150, verbose_name='Bot Url')),
            ],
            options={
                'verbose_name': 'telegram Bot',
                'verbose_name_plural': 'telegram Bots',
            },
        ),
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('chat_name', models.CharField(max_length=100, verbose_name='Chat Name')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegrambot', to='users.telegrambot')),
            ],
            options={
                'verbose_name': 'chat id',
                'verbose_name_plural': 'chat ids',
            },
        ),
    ]
