# Generated by Django 3.2.20 on 2023-09-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Opened', max_length=50, verbose_name='Task Status'),
        ),
    ]
