# Generated by Django 3.2.20 on 2023-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230921_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='agent_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Agent Note'),
        ),
    ]
