# Generated by Django 3.2.20 on 2023-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_agent_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Deadline Time'),
        ),
    ]
